alias web='cd /var/www'
alias d8='cd /var/www/drupal8'
alias d7='cd /var/www/drupal7'
alias egrep='egrep --exclude=.tags --exclude-dir=.git '
alias grep='grep --exclude=.tags --exclude-dir=.git '
alias jctags='ctags -f .tags .'
alias jdrush='/usr/share/drush/drush.launcher'
alias dtest='sudo -u www-data php core/scripts/run-tests.sh --verbose --non-html --color  --url http://d8.local'
alias dunit='export SIMPLETEST_DB=mysql://root@localhost/drupal8 && ../vendor/bin/phpunit'
